name: infrastructure

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Choose environment"
        required: true
        default: "dev"

jobs:
  create-resources:
    env:
      TF_VAR_ARM_SUBSCRIPTION_ID: ${{secrets.ARM_SUBSCRIPTION_ID}}
      TF_VAR_db_password: ${{secrets.db_password}}
      TF_VAR_db_admin: ${{secrets.db_admin}}
      TF_VAR_author: ${{secrets.author}}
      TF_VAR_resource_prefix: ${{secrets.resource_prefix}}
      TF_VAR_resource_group_name: ${{secrets.resource_group_name}}
      TF_VAR_resource_group_location: ${{secrets.resource_group_location}}
      TF_VAR_be_image_name_and_tag: ${{ secrets.be_image_name_and_tag}}
      TF_VAR_fe_image_name_and_tag: ${{ secrets.fe_image_name_and_tag}}
      TF_VAR_contact_person_email: ${{ secrets.contact_person_email }}
      TF_VAR_contact_person_name: ${{ secrets.contact_person_name }}

    name: "Builds the infrastructure on Azure"

    runs-on: ubuntu-latest
    steps:
      - name: "Checkout the branch"

        uses: "actions/checkout@v5"

      - name: Azure Login (Service Principal)
        uses: azure/login@v2
        with:
          creds: ${{secrets.AZURE_CREDS}}

      - name: HashiCorp - Setup Terraform
        uses: hashicorp/setup-terraform@v3.1.2

      - name: "Initialize Terraform"
        working-directory: ./infra
        run: terraform init

      - name: Run Terraform Plan
        working-directory: ./infra
        run: terraform plan -lock=false

      - name: Apply Terraform (Few times due to inconsistent plan errors that just resolve with retry.)
        working-directory: ./infra
        run: terraform apply -auto-approve || terraform apply -auto-approve || terraform apply -auto-approve

      - name: Get Gateway Public IP
        id: get_ip
        working-directory: ./infra
        run: |
          ip=$(terraform output -raw agw_ips)
          echo "gateway_ip=$ip" >> $GITHUB_OUTPUT
