name: Build & Push Frontend

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Choose environment"
        required: true
        default: "dev"

jobs:
  create-resources:
    env:
      TF_VAR_db_user: ${{secrets.DB_USER}}
      TF_VAR_ARM_SUBSCRIPTION_ID: ${{secrets.ARM_SUBSCRIPTION_ID}}
      TF_VAR_db_password: ${{secrets.db_password}}
      TF_VAR_db_admin: ${{secrets.db_admin}}
      TF_VAR_author: ${{secrets.author}}
      TF_VAR_resource_prefix: ${{secrets.resource_prefix}}
      TF_VAR_resource_group_name: ${{secrets.resource_group_name}}
      TF_VAR_resource_group_location: ${{secrets.resource_group_location}}
      TF_VAR_be_port: 80
      TF_VAR_fe_port: 80

    name: "Builds the infrastructure on Azure"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout the branch"
        uses: "actions/checkout@v5"

      - name: Azure Login (Service Principal)
        uses: azure/login@v2
        with:
          creds: ${{secrets.AZURE_CREDS}}

      - name: HashiCorp - Setup Terraform
        uses: hashicorp/setup-terraform@v3.1.2

      - name: "Initialize Terraform"
        run: terraform init

      - name: Export the image names
        run: |
          echo "TF_VAR_be_image_name=${{env.be_image_name}}" >> $GITHUB_ENV
          echo "TF_VAR_fe_image_name=${{env.fe_image_name}}" >> $GITHUB_ENV

      - name: Run Terraform Plan
        run: terraform plan

      - name: Apply Terraform (Few times due to inconsistent plan errors that just resolve with retry.)
        run: terraform apply -auto-approve || terraform apply -auto-approve || terraform apply -auto-approve

      - name: Get Gateway Public IP
        id: get_ip
        working-directory: ./infra
        run: |
          ip=$(terraform output -raw agw_ips)
          echo "gateway_ip=$ip" >> $GITHUB_OUTPUT
